version: '3.8'
#containers => services
services:
  mysql-container:
    image: mysql
    container_name: mysql-container
    ports:
      - 3308:3306    
    volumes:
      - C:\Users\6137\work\AWS\Git\mysql:/var/lib/mysql
      # - mysql-springboot-config-deamond:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Abc@123456789
      MYSQL_ROOT_PASSWORD: Abc@123456789
      MYSQL_DATABASE: TodoDB
  springboot-docker-container:
    image: spring-example:v1.0
    container_name: springboot-docker-container
    ports:
      - 8085:8083
    volumes:
      - ./:/app
    networks:
      - backend
#create network     
networks:
  backend:
    name: todo-app-network
# volumes:
#   mysql-springboot-data: C:\Users\6137\work\AWS\Git\mysql
  # mysql-springboot-config-deamond: C:\Users\6137\work\AWS\Git\config-deamond